version: '3.8'

services:
  api:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=4000
      - NODE_ENV=development
      # This pulls your Atlas link directly from the .env file
      - MONGODB_URI=${MONGODB_URI}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: